# Generated by Django 3.0 on 2020-01-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=120)),
                ('Product_Type', models.CharField(max_length=120)),
                ('Product_Price', models.DecimalField(decimal_places=3, max_digits=20000)),
                ('Product_Description', models.TextField(blank=True)),
                ('Product_Quantity', models.IntegerField()),
                ('img', models.FileField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='upload_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.CharField(max_length=140)),
                ('File_Type', models.CharField(max_length=140, null=True)),
                ('pdf', models.FileField(null=True, upload_to='files/')),
            ],
        ),
    ]
